export const ALL_PRODUCTS = [
  {
    id: 1,
    name: 'Classic Crew Tee',
    price: 29.99,
    category: 'Tops',
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=900&fit=crop',
    badge: 'Best Seller' as string | null,
    description:
      'A wardrobe cornerstone crafted from 100% organic ring-spun cotton. The relaxed crew-neck silhouette sits perfectly off the shoulder and the pre-shrunk jersey keeps its shape wash after wash. Whether worn solo or layered under an open shirt, this tee elevates any casual look without effort.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#1a1a2e', '#fff', '#f7444e', '#e5e7eb'],
    stock: 42,
  },
  {
    id: 2,
    name: 'Slim Fit Chinos',
    price: 59.99,
    category: 'Bottoms',
    rating: 4.6,
    reviews: 87,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=900&fit=crop',
    badge: null,
    description:
      'Tailored from a stretch-cotton blend, these slim-fit chinos move with you from desk to dinner. A mid-rise waist and tapered leg create a clean line, while the subtle texture adds depth without bulk. Machine washable and wrinkle-resistant — your go-to for polished, relaxed dressing.',
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['#8B7355', '#002c3e', '#6b7280'],
    stock: 18,
  },
  {
    id: 3,
    name: 'Oxford Button-Down',
    price: 49.99,
    category: 'Shirts',
    rating: 4.7,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=900&fit=crop',
    badge: 'New',
    description:
      'Woven from a 120-count Oxford cloth, this button-down strikes the ideal balance between casual and smart. The spread collar works open at the neck or buttoned up under a blazer. Garment-washed for a lived-in softness straight out of the bag — no breaking-in required.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#fff', '#93c5fd', '#fde68a'],
    stock: 31,
  },
  {
    id: 4,
    name: 'Floral Summer Dress',
    price: 69.99,
    category: 'Dresses',
    rating: 4.9,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=900&fit=crop',
    badge: 'Trending',
    description:
      'Crafted from lightweight viscose, this midi dress drapes beautifully and breathes in warm weather. The hand-painted floral print is exclusive to this season, with a smocked bodice that fits a range of sizes and adjustable tie straps for your perfect length.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#fde68a', '#fbcfe8', '#a7f3d0'],
    stock: 9,
  },
  {
    id: 5,
    name: 'Leather Bomber',
    price: 119.99,
    category: 'Outerwear',
    rating: 4.8,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=900&fit=crop',
    badge: 'New',
    description:
      'Full-grain leather exterior, satin lining, and a ribbed hem and cuffs give this bomber a timeless, premium feel. The YKK zip glides effortlessly and two side pockets keep essentials within easy reach. Ages beautifully — the more you wear it, the better it looks.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#1a1a1a', '#8B4513', '#006b3c'],
    stock: 5,
  },
  {
    id: 6,
    name: 'Relaxed Linen Shirt',
    price: 44.99,
    category: 'Shirts',
    rating: 4.5,
    reviews: 91,
    image: 'https://images.unsplash.com/photo-1589992896096-94e6e80a7e67?w=800&h=900&fit=crop',
    badge: null,
    description:
      'Pure Belgian linen, stone-washed for a naturally crumpled texture that looks intentionally effortless. A boxy, relaxed silhouette with dropped shoulders and a curved hem sits perfectly untucked. Gets softer and more characterful with every wear and wash.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#f5f0e8', '#d4c5a9', '#8fbc8f'],
    stock: 27,
  },
  {
    id: 7,
    name: 'High-Waist Jeans',
    price: 74.99,
    category: 'Bottoms',
    rating: 4.7,
    reviews: 178,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&h=900&fit=crop',
    badge: 'Best Seller',
    description:
      'Made from a 98% cotton selvedge denim with just 2% stretch for structure that holds its shape. A true high-rise waist emphasises the silhouette while the straight leg creates a flattering line from hip to ankle. Five-pocket construction and a zip fly finished with a branded button.',
    sizes: ['24', '26', '28', '30', '32', '34'],
    colors: ['#1a2744', '#4a5568', '#94a3b8'],
    stock: 22,
  },
  {
    id: 8,
    name: 'Knit Pullover Sweater',
    price: 64.99,
    category: 'Tops',
    rating: 4.6,
    reviews: 143,
    image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&h=900&fit=crop',
    badge: null,
    description:
      'A 12-gauge merino-wool knit with a brushed interior that locks in warmth without adding bulk. The relaxed fit and ribbed hem, cuffs and collar give clean structure to an otherwise easy silhouette. Gentle hand-wash recommended; lay flat to dry to preserve the knit.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#d4a574', '#6b7280', '#002c3e', '#e5e7eb'],
    stock: 14,
  },
  {
    id: 9,
    name: 'Wrap Midi Dress',
    price: 79.99,
    category: 'Dresses',
    rating: 4.8,
    reviews: 267,
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&h=900&fit=crop',
    badge: 'Trending',
    description:
      'The wrap silhouette is universally flattering — a deep V-neckline, adjustable tie waist, and fluid midi hem that moves gracefully as you walk. Cut from matte crepe that resists static, this dress takes you effortlessly from brunch to evening with just a shoe change.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#1a1a2e', '#7c3aed', '#f59e0b'],
    stock: 33,
  },
  {
    id: 10,
    name: 'Oversized Hoodie',
    price: 54.99,
    category: 'Tops',
    rating: 4.9,
    reviews: 445,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=900&fit=crop',
    badge: 'Best Seller',
    description:
      'Loopback 100% cotton fleece — thick, brushed, and impossibly cosy. Dropped shoulders, an oversized fit, and a kangaroo pocket with a hidden zip compartment. Double-stitched seams and a printed-not-embroidered logo ensure it survives a thousand washes.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#374151', '#e5e7eb', '#f7444e', '#002c3e'],
    stock: 68,
  },
  {
    id: 11,
    name: 'Trench Coat',
    price: 149.99,
    category: 'Outerwear',
    rating: 4.7,
    reviews: 39,
    image: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800&h=900&fit=crop',
    badge: 'New',
    description:
      'A modern interpretation of a British classic. Water-repellent poplin with a removable wool-blend lining takes this trench across seasons. D-ring epaulettes, storm flap, and adjustable belt are all faithfully present — as is a hidden interior zip pocket for your essentials.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#c8a882', '#1a1a2e', '#4a5568'],
    stock: 7,
  },
  {
    id: 12,
    name: 'Pleated Midi Skirt',
    price: 52.99,
    category: 'Bottoms',
    rating: 4.6,
    reviews: 112,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&h=900&fit=crop',
    badge: null,
    description:
      'Fine knife pleats in a satin-finish polyester give this midi skirt movement and sheen without weight. A hidden elastic waistband with a side button closure ensures a clean front view. Versatile enough to dress up with heels or down with trainers.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['#1a1a2e', '#c8a882', '#f9a8d4'],
    stock: 19,
  },
  {
    id: 13,
    name: 'Satin Blouse',
    price: 47.99,
    category: 'Shirts',
    rating: 4.5,
    reviews: 76,
    image: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&h=900&fit=crop',
    badge: null,
    description:
      'Charmeuse satin cut on the bias so it drapes and moves with your body. A self-tie neck bow adds a polished flourish that can be styled multiple ways — bow tied, open collar, or tucked inside. Wear it with tailored trousers for work or jeans for a dressed-down take.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#f5f5dc', '#fce7f3', '#dbeafe'],
    stock: 11,
  },
  {
    id: 14,
    name: 'Velvet Blazer',
    price: 109.99,
    category: 'Outerwear',
    rating: 4.8,
    reviews: 48,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&h=900&fit=crop',
    badge: 'New',
    description:
      'Crushed velvet in a single-button, notch-lapel cut that reads as formal or fashion depending on how you wear it. A slim fit through the chest and shoulders with just enough ease in the body to layer over a shirt or roll-neck. Lined in a smooth acetate for easy wear.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#1a1a2e', '#7c3aed', '#065f46'],
    stock: 6,
  },
  {
    id: 15,
    name: 'Boho Maxi Dress',
    price: 89.99,
    category: 'Dresses',
    rating: 4.7,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&h=900&fit=crop',
    badge: null,
    description:
      'A floor-grazing silhouette in 100% washed viscose, hand block-printed with an artisan-sourced botanical motif. Elasticated waist, adjustable shoulder ties, and a side split for ease of movement. Each print is slightly unique — no two dresses are exactly alike.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#fef3c7', '#d1fae5', '#fce7f3'],
    stock: 16,
  },
  {
    id: 16,
    name: 'Cargo Joggers',
    price: 62.99,
    category: 'Bottoms',
    rating: 4.6,
    reviews: 234,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=900&fit=crop',
    badge: 'Trending',
    description:
      'Technical-canvas cargo joggers with a hybrid construction — an elasticated waistband and ribbed cuffs for jogger comfort, four cargo pockets with hidden zip closures for utility. A tapered leg keeps the silhouette clean. Brush-lined interior for warmth in cooler weather.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#4a5568', '#1a1a2e', '#4a7c59'],
    stock: 37,
  },
];

export type Product = (typeof ALL_PRODUCTS)[0];

export const BADGE_COLORS: Record<string, string> = {
  'Best Seller': '#f7444e',
  New: '#10b981',
  Trending: '#f59e0b',
};
